apiVersion: v1
kind: Service
metadata:
  name: agent-api
  namespace: stratum
spec:
  selector:
    app: agent-core
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
